# Khôi phục validation H3 sau khi Vertex bị chặn

Notebook này dùng **prompt validation cũ (giới hạn 8192 byte)**. Nó giữ response Qwen/Vertex đã thành công và gọi **DeepSeek-V4-Flash/FPT chỉ cho các request lỗi**. Lần chạy đã lưu có 2.714 request bị CONSUMER_SUSPENDED và 295 request bị lỗi 429; phải retry cả hai nhóm để validation hoàn tất. Bốn bản ghi ReVeal trùng prompt dùng chung request.

**Kết quả là exploratory, trộn model và trộn đời contract giữa validation/test. Không báo cáo điểm này như benchmark một backbone theo contract 24k.** Notebook ghi provider/model thực tế cho từng response và giữ bản gốc trong recovery/original/.

Thứ tự: kiểm kê → gọi thử 1 request → gọi phần còn lại → gộp và kích hoạt recovery → quay lại full-pipeline.ipynb, chạy lại từ Bước 1/2. Không chạy lại CPU fit; bước 1 sẽ dùng lại stage cũ khi marker recovery đã kích hoạt.

In [1]:
from pathlib import Path
import sys
import pandas as pd

ROOT = Path('/mnt/d/JUNIOR/LabThayTho/GRACE-H3-BenchmarkEnsemble')
if not ROOT.exists():
    ROOT = Path('D:/JUNIOR/LabThayTho/GRACE-H3-BenchmarkEnsemble')
ROOT = ROOT.resolve()
sys.path.insert(0, str(ROOT))

from grace_h3v2.recovery import inventory, export_failure_inventory, retry_failed, finalize

STAGE_ID = '5fc21bd7cafff9846aff'
WORKERS = 4
print('Root:', ROOT)
print('Stage:', STAGE_ID)

Root: /mnt/d/JUNIOR/LabThayTho/GRACE-H3-BenchmarkEnsemble
Stage: 5fc21bd7cafff9846aff

## 1. Kiểm kê request lỗi

Bảng đọc các artifact validation đã có và xuất danh sách mẫu lỗi vào recovery/failure_inventory.jsonl; không gọi API. failed_unique_requests là số request cần retry, có thể thấp hơn failed_queries nếu prompt trùng.

In [2]:
report = inventory(ROOT, STAGE_ID)
display(pd.DataFrame(report['runs']))
print('Provider mới:', report['provider'], '| Model:', report['model'])
print('Nhóm lỗi:', {r['run']: r['error_categories'] for r in report['runs']})
print('Danh sách mẫu lỗi:')
display(pd.DataFrame(export_failure_inventory(ROOT, STAGE_ID)))

,run,queries,successful_vertex,failed_queries,failed_unique_requests,saved_journal_rows,error_categories
0,runs/devign/validation/baseline_whitening/f79c...,2724,1886,838,838,0,"{'rate_limited_429': 295, 'consumer_suspended'..."
1,runs/reveal/validation/baseline_whitening/27ee...,2196,25,2171,2167,0,{'consumer_suspended': 2171}

Provider mới: FPT AI Factory | Model: DeepSeek-V4-Flash
Nhóm lỗi: {'runs/devign/validation/baseline_whitening/f79c31718971e534': {'rate_limited_429': 295, 'consumer_suspended': 543}, 'runs/reveal/validation/baseline_whitening/27ee63ea9ec23f93': {'consumer_suspended': 2171}}
Danh sách mẫu lỗi:

,run,rows,file
0,runs/devign/validation/baseline_whitening/f79c...,838,runs/devign/validation/baseline_whitening/f79c...
1,runs/reveal/validation/baseline_whitening/27ee...,2171,runs/reveal/validation/baseline_whitening/27ee...

## 2. Gọi thử đúng một request FPT

Nếu tài khoản/model FPT chưa dùng được, dừng ở đây. Request thành công được ghi ngay vào journal và cache; chạy lại cell này sẽ chọn request kế tiếp.

In [5]:
smoke = retry_failed(ROOT, STAGE_ID, limit=1, workers=1)
print(smoke)
if smoke['errors']:
    raise RuntimeError('Request FPT đầu tiên thất bại; xem recovery/requests trong run tương ứng trước khi chạy hàng loạt.')

FPT retry requests: 1 (stage 5fc21bd7cafff9846aff)
FPT retry 1/1; ok=1, errors=0
{'attempted': 1, 'ok': 1, 'errors': 0, 'remaining': 3004}

## 3. Retry toàn bộ request lỗi còn lại

Có thể ngắt và chạy lại cell. Những request FPT đã thành công được lấy từ journal/cache, không gọi lại. Nếu còn errors hoặc remaining, xử lý nguyên nhân rồi chạy lại cell này.

In [6]:
result = retry_failed(ROOT, STAGE_ID, limit=0, workers=WORKERS)
print(result)
if result['remaining']:
    raise RuntimeError(f"Vẫn còn {result['remaining']} request chưa thành công; chạy lại cell sau khi xử lý lỗi.")

FPT retry requests: 3004 (stage 5fc21bd7cafff9846aff)
FPT retry 25/3004; ok=25, errors=0
FPT retry 50/3004; ok=50, errors=0
FPT retry 75/3004; ok=75, errors=0
FPT retry 100/3004; ok=100, errors=0
FPT retry 125/3004; ok=125, errors=0
FPT retry 150/3004; ok=150, errors=0
FPT retry 175/3004; ok=175, errors=0
FPT retry 200/3004; ok=200, errors=0
FPT retry 225/3004; ok=225, errors=0
FPT retry 250/3004; ok=250, errors=0
FPT retry 275/3004; ok=275, errors=0
FPT retry 300/3004; ok=300, errors=0
FPT retry 325/3004; ok=325, errors=0
FPT retry 350/3004; ok=350, errors=0
FPT retry 375/3004; ok=375, errors=0
FPT retry 400/3004; ok=400, errors=0
FPT retry 425/3004; ok=425, errors=0
FPT retry 450/3004; ok=450, errors=0
FPT retry 475/3004; ok=475, errors=0
FPT retry 500/3004; ok=500, errors=0
FPT retry 525/3004; ok=525, errors=0
FPT retry 550/3004; ok=550, errors=0
FPT retry 575/3004; ok=575, errors=0
FPT retry 600/3004; ok=600, errors=0
FPT retry 625/3004; ok=625, errors=0
FPT retry 650/3004; ok=650, errors=0
FPT retry 675/3004; ok=675, errors=0
FPT retry 700/3004; ok=700, errors=0
FPT retry 725/3004; ok=725, errors=0
FPT retry 750/3004; ok=750, errors=0
FPT retry 775/3004; ok=775, errors=0
FPT retry 800/3004; ok=800, errors=0
FPT retry 825/3004; ok=825, errors=0
FPT retry 850/3004; ok=850, errors=0
FPT retry 875/3004; ok=875, errors=0
FPT retry 900/3004; ok=900, errors=0
FPT retry 925/3004; ok=925, errors=0
FPT retry 950/3004; ok=950, errors=0
FPT retry 975/3004; ok=975, errors=0
FPT retry 1000/3004; ok=1000, errors=0
FPT retry 1025/3004; ok=1025, errors=0
FPT retry 1050/3004; ok=1050, errors=0
FPT retry 1075/3004; ok=1075, errors=0
FPT retry 1100/3004; ok=1100, errors=0
FPT retry 1125/3004; ok=1125, errors=0
FPT retry 1150/3004; ok=1150, errors=0
FPT retry 1175/3004; ok=1175, errors=0
FPT retry 1200/3004; ok=1200, errors=0
FPT retry 1225/3004; ok=1225, errors=0
FPT retry 1250/3004; ok=1250, errors=0
FPT retry 1275/3004; ok=1275, errors=0
FPT retry 1300/3004; ok=1300, errors=0
FPT retry 1325/3004; ok=1325, errors=0
FPT retry 1350/3004; ok=1350, errors=0
FPT retry 1375/3004; ok=1375, errors=0
FPT retry 1400/3004; ok=1400, errors=0
FPT retry 1425/3004; ok=1425, errors=0
FPT retry 1450/3004; ok=1450, errors=0
FPT retry 1475/3004; ok=1475, errors=0
FPT retry 1500/3004; ok=1500, errors=0
FPT retry 1525/3004; ok=1525, errors=0
FPT retry 1550/3004; ok=1550, errors=0
FPT retry 1575/3004; ok=1575, errors=0
FPT retry 1600/3004; ok=1600, errors=0
FPT retry 1625/3004; ok=1625, errors=0
FPT retry 1650/3004; ok=1650, errors=0
FPT retry 1675/3004; ok=1675, errors=0
FPT retry 1700/3004; ok=1700, errors=0
FPT retry 1725/3004; ok=1725, errors=0
FPT retry 1750/3004; ok=1750, errors=0
FPT retry 1775/3004; ok=1775, errors=0
FPT retry 1800/3004; ok=1800, errors=0
FPT retry 1825/3004; ok=1825, errors=0
FPT retry 1850/3004; ok=1850, errors=0
FPT retry 1875/3004; ok=1875, errors=0
FPT retry 1900/3004; ok=1900, errors=0
FPT retry 1925/3004; ok=1925, errors=0
FPT retry 1950/3004; ok=1950, errors=0
FPT retry 1975/3004; ok=1975, errors=0
FPT retry 2000/3004; ok=2000, errors=0
FPT retry 2025/3004; ok=2025, errors=0
FPT retry 2050/3004; ok=2050, errors=0
FPT retry 2075/3004; ok=2075, errors=0
FPT retry 2100/3004; ok=2100, errors=0
FPT retry 2125/3004; ok=2125, errors=0
FPT retry 2150/3004; ok=2150, errors=0
FPT retry 2175/3004; ok=2175, errors=0
FPT retry 2200/3004; ok=2200, errors=0
FPT retry 2225/3004; ok=2225, errors=0
FPT retry 2250/3004; ok=2250, errors=0
FPT retry 2275/3004; ok=2275, errors=0
FPT retry 2300/3004; ok=2300, errors=0
FPT retry 2325/3004; ok=2325, errors=0
FPT retry 2350/3004; ok=2350, errors=0
FPT retry 2375/3004; ok=2375, errors=0
FPT retry 2400/3004; ok=2400, errors=0
FPT retry 2425/3004; ok=2425, errors=0
FPT retry 2450/3004; ok=2450, errors=0
FPT retry 2475/3004; ok=2475, errors=0
FPT retry 2500/3004; ok=2500, errors=0
FPT retry 2525/3004; ok=2525, errors=0
FPT retry 2550/3004; ok=2550, errors=0
FPT retry 2575/3004; ok=2575, errors=0
FPT retry 2600/3004; ok=2600, errors=0
FPT retry 2625/3004; ok=2625, errors=0
FPT retry 2650/3004; ok=2650, errors=0
FPT retry 2675/3004; ok=2675, errors=0
FPT retry 2700/3004; ok=2700, errors=0
FPT retry 2725/3004; ok=2725, errors=0
FPT retry 2750/3004; ok=2750, errors=0
FPT retry 2775/3004; ok=2775, errors=0
FPT retry 2800/3004; ok=2800, errors=0
FPT retry 2825/3004; ok=2825, errors=0
FPT retry 2850/3004; ok=2850, errors=0
FPT retry 2875/3004; ok=2875, errors=0
FPT retry 2900/3004; ok=2900, errors=0
FPT retry 2925/3004; ok=2925, errors=0
FPT retry 2950/3004; ok=2950, errors=0
FPT retry 2975/3004; ok=2975, errors=0
FPT retry 3000/3004; ok=3000, errors=0
FPT retry 3004/3004; ok=3004, errors=0
{'attempted': 3004, 'ok': 3004, 'errors': 0, 'remaining': 0}

## 4. Gộp response và quay lại full pipeline

Cell này chỉ chạy khi mọi request lỗi đã có response FPT thành công. Nó giữ ba file gốc trong recovery/original/, tạo lại predictions/summary, rồi bật marker recovery. Sau đó khởi động lại kernel riêng của full-pipeline.ipynb để nạp mã workflow mới, rồi chạy từ Bước 1 hoặc Bước 2. Bước validation sẽ nhận status=complete, mixed_model_recovery=True.

In [7]:
marker = finalize(ROOT, STAGE_ID)
display(pd.DataFrame(marker['runs']))
print('Recovery active:', ROOT / 'runs/h3v2/mixed_model_recovery.json')
print('Quay lại notebooks/full-pipeline.ipynb. Đây là kết quả exploratory trộn Qwen/Vertex và DeepSeek/FPT.')

,run,providers,predictions_sha256
0,runs/devign/validation/baseline_whitening/f79c...,"{'Vertex AI': 1886, 'FPT AI Factory': 838}",2bf7205d1ef20c32c2bd24dfe57280b1aff4ac1b1a24ce...
1,runs/reveal/validation/baseline_whitening/27ee...,"{'FPT AI Factory': 2171, 'Vertex AI': 25}",03499f2cf242c2ea561b4b8e23a27b7ec55f67795f0840...

Recovery active: /mnt/d/JUNIOR/LabThayTho/GRACE-H3-BenchmarkEnsemble/runs/h3v2/mixed_model_recovery.json
Quay lại notebooks/full-pipeline.ipynb. Đây là kết quả exploratory trộn Qwen/Vertex và DeepSeek/FPT.